# NeonRoot image definition for {{image}}.
# Edit this to define the environment, then `neonroot image build {{image}}`
# to build it and save its data into the vault (so it runs offline).
FROM docker.io/library/archlinux:latest

RUN pacman -Syu --noconfirm base-devel git && \
    pacman -Scc --noconfirm

WORKDIR /workspace
CMD ["/bin/bash"]
